### ISSUE TITLE
evetime returns server local time, not UTC

### ISSUE THREAD

**Issue by colcrunch** [zdhoward/dankbot#1]
Was just browsing python discord bots for eve, and noticed that your evetime command does not return the correct time unless the server time is set to UTC.

Instead of `datetime.datetime.now() + timedelta(hours=0)` you should use `datetime.datetime.utcnow()`.

**Comment by zdhoward** [comment]
Thanks for the tip, I've made the change now :)
The rest of it is still a mess lol
